<?php
/**
 * @var $block IWD\CheckoutConnector\Block\Frame
 */
?>

<div class="iwd-checkout-iframe-wrapper">

    <iframe id="<?= $block->escapeHtmlAttr($block->getCheckoutIframeId()) ?>"
            src="<?= $block->escapeUrl($block->getFrameUrl()) ?>"
            data-mage-init='<?= $block->escapeHtmlAttr($block->getJsonConfig()) ?>'
            frameborder="0"
            scrolling="no"
            allow="payment"
            class="iwd-checkout-iframe-js"
            onload="this.dataset.loaded = 'true'">
    </iframe>
    <script src="https://2258284559.nxcli.net/staging/public/js/skeleton-loader.js"></script>
</div>

<script type="text/javascript">
    require([
            'jquery',
            'IWD_CheckoutConnector/js/libs/iframeResizer'
        ],
        function ($, iframeResizer) {
            // Resize Iframe
            iframeResizer({log: false, checkOrigin: false}, '#<?= $block->escapeJs($block->getCheckoutIframeId()) ?>');

            let changeUrlAction = function (event) {
                if (event.data.changeUrlAction === 'edit_cart') {
                    window.location.href = '<?= $block->escapeJs($block->getEditCartUrl()) ?>';
                } else if (event.data.changeUrlAction === 'authenticate') {
                    let data = {username: event.data.login, password: event.data.password};

                    $.ajax({
                        dataType: "json",
                        method: "POST",
                        url: '<?= $block->escapeJs($block->getLoginUrl()) ?>',
                        data: JSON.stringify(data)
                    }).done(function (response) {
                        if (response.errors) {
                            sendMessage(response.message);
                        } else {
                            location.reload(true);
                        }
                    }).fail(function () {
                        let msg = "<?= $block->escapeJs(__('Could not authenticate. Please try again later')) ?>";
                        sendMessage(msg);
                    });
                } else if (event.data.changeUrlAction === 'reset_pass') {
                    window.location.href = '<?= $block->escapeJs($block->getResetPasswordUrl()) ?>';
                }
            };

            let sendMessage = function (msg) {
                document.getElementById('<?= $block->escapeJs($block->getCheckoutIframeId()) ?>').contentWindow.postMessage({
                    'action': 'sendMassage',
                    'message': msg
                }, '*');
            };

            let actionSuccess = function (event) {
                if (event.data.actionSuccess) {
                    let successUrl = '<?= $block->escapeJs($block->getSuccessActionUrl()) ?>',
                        successParams = event.data.actionSuccess;

                    window.location.href = successUrl + '?' + successParams;
                }
            };

            if (window.addEventListener) {
                window.addEventListener("message", changeUrlAction, false);
                window.addEventListener("message", actionSuccess, false);
            } else if (window.attachEvent) {
                window.attachEvent("onmessage", changeUrlAction);
                window.attachEvent("onmessage", actionSuccess);
            }
        }
    );
</script>
