<div class="offline-payment">
    <div class="title">
        <b><?= $block->escapeHtml(__('Title')) ?>:</b> <?= $block->escapeHtml($this->getTitle()) ?>
    </div>
    <?php if($this->getPayableTo() && !empty($this->getPayableTo())):?>
        <div class="payable_to">
            <b><?= $block->escapeHtml(__('Payable To')) ?>:</b> <?= $block->escapeHtml($this->getPayableTo()) ?>
        </div>
    <?php endif;?>
    <?php if($this->getMailingAddress() && !empty($this->getMailingAddress())):?>
        <div class="mailing_address">
            <b><?= $block->escapeHtml(__('Mailing Address')) ?>:</b> <?= $block->escapeHtml($this->getMailingAddress()) ?>
        </div>
    <?php endif;?>
    <?php if($this->getInstruction() && !empty($this->getInstruction())):?>
        <div class="instruction">
            <b><?= $block->escapeHtml(__('Instructions')) ?>:</b> <?= $block->escapeHtml($this->getInstruction()) ?>
        </div>
    <?php endif;?>
    <?php if($this->getExtraDetails() && !empty($this->getExtraDetails())):?>
        <div class="extra_details">
            <b><?= $block->escapeHtml(__('Extra Details')) ?>:</b> <?= $block->escapeHtml($this->getExtraDetails()) ?>
        </div>
    <?php endif;?>
    <?php if($this->getPONumber() && !empty($this->getPONumber())):?>
        <div class="po_number">
            <b><?= $block->escapeHtml($this->getFieldName() ?? __('Purchase Order Number')) ?>:</b> <?= $block->escapeHtml($this->getPONumber()) ?>
        </div>
    <?php endif;?>
</div>
<style>
    .offline-payment div{margin: 5px 0;}
</style>
