<div class="offline-payment">
    <div class="title">
        <b>Payment Title</b> <?php echo $this->getTitle(); ?>
    </div>
    <?php if($this->getPayableTo() && !empty($this->getPayableTo())):?>
        <div class="payable_to">
            <b>Make Check Payable to</b> <?php echo $this->getPayableTo(); ?>
        </div>
    <?php endif;?>
    <?php if($this->getMailingAddress() && !empty($this->getMailingAddress())):?>
        <div class="mailing_address">
            <b>Send Check to</b> <?php echo $this->getMailingAddress(); ?>
        </div>
    <?php endif;?>
    <?php if($this->getInstruction() && !empty($this->getInstruction())):?>
        <div class="instruction">
            <b>Instruction</b> <?php echo $this->getInstruction(); ?>
        </div>
    <?php endif;?>
    <?php if($this->getExtraDetails() && !empty($this->getExtraDetails())):?>
        <div class="extra_details">
            <b>Extra Details</b> <?php echo $this->getExtraDetails(); ?>
        </div>
    <?php endif;?>
    <?php if($this->getPONumber() && !empty($this->getPONumber())):?>
        <div class="po_number">
            <b>Purchase Order Number</b> <?php echo $this->getPONumber(); ?>
        </div>
    <?php endif;?>
</div>
<style>
    .offline-payment div{margin: 5px 0;}
</style>
