<script>
    require([
        'Magento_Customer/js/customer-data'
    ], function (customerData) {
        customerData.invalidate(['cart']);
    });
</script>
<?php if(count($this->getPaymentMethodeDetails()) > 1): ?>
    <div class="checkout-success" style="margin-top: 20px;">
        <h3>Dominate Payment Method Details</h3>
        <?php foreach ($this->getPaymentMethodeDetails() as $key => $detail):?>
            <div class="detail">
                <span class="key">
                    <strong>
                        <?php echo str_replace('_',' ',$key); ?>
                    </strong>
                </span>
                <span class="detail">
                    <?php echo $detail; ?>
                </span>
            </div>
        <?php endforeach;?>
    </div>
    <style>
        .detail{
            margin: 10px 0;
        }
        .detail .key{
            text-transform: capitalize;
        }
    </style>
<?php endif;?>
