<script>
    require(['Magento_Customer/js/customer-data', 'domReady!'], function (customerData) {
        var sections = ['cart'];

        try {
            customerData.initStorage();
        } catch(e) {}

        customerData.invalidate(sections);
        customerData.reload(sections, true);
    });
</script>

<?php if($this->getPaymentMethodDetails()): ?>
    <div class="dominate-payment-details-wrapper">
        <?php foreach ($this->getPaymentMethodDetails() as $title => $content):?>
            <p>
                <strong><?php echo $title; ?>: </strong>
                <span><?php echo $content; ?></span>
            </p>
        <?php endforeach;?>
    </div>
<?php endif;?>