<?php
/**
 * @var IWD\CheckoutConnector\Block\Adminhtml\Order\AdditionalFields $block
 */
?>
<?php foreach ((array)$block->getPersonalDetails() as $label => $value) : ?>
    <?php if (empty($value)) continue; ?>
    <tr>
        <th class="label"><?= $block->escapeHtml($label ?? '') ?> </th>
        <td>
            <?php if (is_object($value)) {
                foreach ($value as $optionLabel => $optionValue) {
                    ?>
                    <br> <span><?= $block->escapeHtml($optionLabel) ?>: </span><span><?= $block->escapeHtml($block->parseOption($optionValue)) ?></span>
                    <?php
                }
            } else {
                echo $block->escapeHtml($value);
            } ?>
        </td>
    </tr>
<?php endforeach; ?>
