<?php
/**
 * @var IWD\CheckoutConnector\Block\Shortcut\PayPalButton $block
 */

$containerId = $block->getContainerId();
$merchantId = $block->getMerchantId() ? $block->getMerchantId() : ''
?>
<?php if($block->getPaypalStatus()): ?>
    <script>
        require([
            "jquery"
        ], function ($) {
            if (typeof window.paypal === 'undefined') {
                let scriptParams = {
                    "client-id": "<?= $block->getClientId() ?>",
                    "commit": "false",
                    "intent": "authorize",
                    "components": "buttons,messages,applepay",
                    "vault": "false",
                    "merchant-id": "<?= $merchantId ?>",
                    "currency": "<?= $block->getCurrencyCode() ?>",
                    "data-partner-attribution-id": "<?= $block->getPayPalBnCode() ?>"
                };

                const enableFunding = "<?= $block->getEnableFundingParam() ?>";

                if(enableFunding !== "") {
                    scriptParams['enable-funding'] = enableFunding;
                }

                window
                    .paypalLoadScript(scriptParams)
                    .then(() => {
                        renderPayPalSmartButtons();
                    });
            } else {
                renderPayPalSmartButtons();
            }

            function renderPayPalSmartButtons() {
                const container = $('#<?= $containerId ?>-wrapper'),
                      element   = $('<div>').attr({
                          'id': '<?= $containerId ?>',
                          'data-mage-init': '<?= $block->getJsonConfig($containerId) ?>'
                      });

                container.html(element).trigger('contentUpdated');
            }
        });
    </script>
    <div id='<?= $containerId ?>-wrapper' class="iwd-paypal-wrapper"></div>
<?php endif; ?>