<?php
/**
 * @var IWD\CheckoutConnector\Block\Shortcut\PayPalButton $block
 */

$containerId = $block->getContainerId();
$merchantId = $block->getMerchantId() ? $block->getMerchantId() : ''
?>
<?php if($block->getPaypalStatus()): ?>
    <script>
        if (typeof window.paypal === 'undefined') {
            window.paypalLoadScript(
                {
                    "client-id": "<?= $block->getClientId() ?>",
                    "commit": "false",
                    "intent": "capture",
                    "components": "buttons,messages",
                    "vault": "true",
                    "merchant-id": "<?=$merchantId?>",
                    "currency": "<?=$block->getCurrencyCode()?>",
                    "data-partner-attribution-id": "<?= $block->getPayPalBnCode() ?>"
                }
            )
        }
    </script>
    <div id='<?= $containerId ?>' class="iwd-paypal-wrapper" data-mage-init='<?= $block->getJsonConfig($containerId) ?>'></div>
<?php endif; ?>