<?php
/**
 * @var IWD\CheckoutConnector\Block\Shortcut\PayPalButton $block
 */

$containerId = $block->getContainerId();
$merchantId = $block->getMerchantId() ? $block->getMerchantId() : ''
?>
<?php if($block->getPaypalStatus()): ?>
    <script>
        require([
            "jquery",
            "dominatePayPalJS"
        ], function ($) {
            if (typeof window.paypal === 'undefined') {
                let scriptParams = {
                    "client-id": "<?= $block->escapeJs($block->getClientId()) ?>",
                    "commit": "false",
                    "intent": "authorize",
                    "components": "buttons,messages,applepay,googlepay",
                    "vault": "false",
                    "merchant-id": "<?= $block->escapeJs($merchantId) ?>",
                    "currency": "<?= $block->escapeJs($block->getCurrencyCode()) ?>",
                    "data-partner-attribution-id": "<?= $block->escapeJs($block->getPayPalBnCode()) ?>"
                };

                const enableFunding = "<?= $block->escapeJs($block->getEnableFundingParam()) ?>";

                if(enableFunding !== "") {
                    scriptParams['enable-funding'] = enableFunding;
                }

                window
                    .paypalLoadScript(scriptParams)
                    .then(() => {
                        renderPayPalSmartButtons();
                    });
            } else {
                renderPayPalSmartButtons();
            }

            function renderPayPalSmartButtons() {
                const container = $('#<?= $block->escapeJs($containerId) ?>-wrapper'),
                      element   = $('<div>').attr({
                          'id': '<?= $block->escapeJs($containerId) ?>',
                          'data-mage-init': '<?= $block->escapeJs($block->getJsonConfig($containerId)) ?>'
                      });

                container.html(element).trigger('contentUpdated');
            }
        });
    </script>
    <div id='<?= $block->escapeHtmlAttr($containerId) ?>-wrapper' class="iwd-paypal-wrapper"></div>
<?php endif; ?>
